.darn_env <- new.env(parent = emptyenv())

#' Calls a function, records the first argument
#'
#' For use by the \code{Makefile} generated by \code{\link{create_makefile}}.
#'
#' @param file The name of the R script
#' @param fun The function that should be called to process the R script. The
#'   \code{file} argument will be bassed as first argument to that function.
#' @param ... Additional arguments passed to \code{fun}.
#'
#' @examples
#' \dontrun{
#' run("A.R", source)
#' run("A.R", rmarkdown::render)
#' run("A.R", ezknitr::ezspin)
#' }
#' @export
run <- function(file, fun, ...) {
  stopifnot(!exists("current_file", .darn_env))
  .darn_env$current_file <- normalizePath(file)
  on.exit(rm("current_file", .darn_env))
  fun(file, ...)
}
